USE [master]
GO
/****** Object:  Database [BookRental]    Script Date: 7/14/2021 6:20:15 PM ******/
CREATE DATABASE [BookRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookRental', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BookRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookRental_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BookRental_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BookRental] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookRental] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookRental] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookRental] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookRental] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookRental] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookRental] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BookRental] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookRental] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookRental] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookRental] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookRental] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookRental] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookRental] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookRental] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookRental] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookRental] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookRental] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BookRental] SET  MULTI_USER 
GO
ALTER DATABASE [BookRental] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookRental] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BookRental] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BookRental] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BookRental] SET QUERY_STORE = OFF
GO
USE [BookRental]
GO
/****** Object:  Table [dbo].[tblCategory]    Script Date: 7/14/2021 6:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblCategory](
	[categoryID] [varchar](10) NOT NULL,
	[cateName] [varchar](100) NULL,
	[urlimg] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[categoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblOrderDetail]    Script Date: 7/14/2021 6:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblOrderDetail](
	[detailID] [varchar](10) NOT NULL,
	[orderID] [varchar](10) NULL,
	[productID] [varchar](10) NULL,
	[quantity] [int] NULL,
	[price] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[detailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblOrders]    Script Date: 7/14/2021 6:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblOrders](
	[orderID] [varchar](10) NOT NULL,
	[userID] [varchar](20) NULL,
	[total] [int] NULL,
	[deliverAddr] [varchar](50) NULL,
	[paymentCheck] [varchar](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[orderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblProduct]    Script Date: 7/14/2021 6:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblProduct](
	[productID] [varchar](10) NOT NULL,
	[bookName] [varchar](100) NULL,
	[price] [float] NULL,
	[quantity] [int] NULL,
	[categoryID] [varchar](10) NULL,
	[Img] [varchar](200) NULL,
	[descr] [varchar](250) NULL,
	[Published] [varchar](100) NULL,
	[Writer] [varchar](100) NULL,
	[Cover] [varchar](100) NULL,
	[Penciler] [varchar](100) NULL,
	[active] [varchar](3) NULL,
PRIMARY KEY CLUSTERED 
(
	[productID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblRoles]    Script Date: 7/14/2021 6:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblRoles](
	[roleID] [varchar](10) NOT NULL,
	[roleName] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[roleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblUsers]    Script Date: 7/14/2021 6:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUsers](
	[userID] [varchar](20) NOT NULL,
	[userName] [nvarchar](50) NULL,
	[phone] [int] NULL,
	[roleID] [varchar](10) NULL,
	[addr] [varchar](50) NULL,
	[pass] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblOrderDetail]  WITH CHECK ADD FOREIGN KEY([orderID])
REFERENCES [dbo].[tblOrders] ([orderID])
GO
ALTER TABLE [dbo].[tblOrderDetail]  WITH CHECK ADD FOREIGN KEY([productID])
REFERENCES [dbo].[tblProduct] ([productID])
GO
ALTER TABLE [dbo].[tblOrders]  WITH CHECK ADD FOREIGN KEY([userID])
REFERENCES [dbo].[tblUsers] ([userID])
GO
ALTER TABLE [dbo].[tblProduct]  WITH CHECK ADD FOREIGN KEY([categoryID])
REFERENCES [dbo].[tblCategory] ([categoryID])
GO
ALTER TABLE [dbo].[tblUsers]  WITH CHECK ADD FOREIGN KEY([roleID])
REFERENCES [dbo].[tblRoles] ([roleID])
GO
USE [master]
GO
ALTER DATABASE [BookRental] SET  READ_WRITE 
GO
